INSERT INTO vehicle (make, model, year, vehicle_description, color, vehicle_type, fuel_type, seating_capacity, size_category, location, price_per_day, is_available_to_rent) VALUES
('Toyota', 'Corolla', 2022, '1.8L 4-Cylinder Engine, Automatic Transmission', 'Silver', 'Sedan', 'Petrol', 5, 'Compact', 'New York', 40, true),
('Honda', 'Civic', 2023, '2.0L 4-Cylinder Engine, Automatic Transmission', 'Black', 'Sedan', 'Petrol', 5, 'Compact', 'Los Angeles', 45, true),
('Tesla', 'Model 3', 2022, 'Electric Motor, Automatic Transmission', 'Red', 'Sedan', 'Electric', 5, 'Compact', 'San Francisco', 60, true),
('Ford', 'Escape', 2023, '2.0L 4-Cylinder Engine, Automatic Transmission', 'Blue', 'SUV', 'Petrol', 5, 'Compact', 'Chicago', 50, true),
('Toyota', 'RAV4', 2022, '2.5L 4-Cylinder Engine, Automatic Transmission', 'White', 'SUV', 'Petrol', 5, 'Compact', 'Houston', 55, true),
('Hyundai', 'Elantra', 2024, '2.0L 4-Cylinder Engine, Automatic Transmission', 'Gray', 'Sedan', 'Petrol', 5, 'Compact', 'Seattle', 42, true),
('Nissan', 'Leaf', 2022, 'Electric Motor, Automatic Transmission', 'Green', 'Hatchback', 'Electric', 5, 'Compact', 'Boston', 50, true),
('Chevrolet', 'Bolt', 2023, 'Electric Motor, Automatic Transmission', 'Silver', 'Hatchback', 'Electric', 5, 'Compact', 'Denver', 55, true),
('Honda', 'CR-V', 2022, '1.5L 4-Cylinder Engine, Automatic Transmission', 'Black', 'SUV', 'Petrol', 5, 'Compact', 'Miami', 50, true),
('Ford', 'Focus', 2023, '2.3L 4-Cylinder Engine, Automatic Transmission', 'Red', 'Sedan', 'Petrol', 5, 'Compact', 'Dallas', 40, true),
('Kia', 'Niro', 2024, '1.6L 4-Cylinder Engine, Automatic Transmission', 'Blue', 'Crossover', 'Petrol', 5, 'Compact', 'San Diego', 45, true),
('Volkswagen', 'Golf', 2022, '2.0L 4-Cylinder Engine, Automatic Transmission', 'White', 'Hatchback', 'Petrol', 5, 'Compact', 'Portland', 50, true),
('BMW', '3 Series', 2023, '2.0L 4-Cylinder Engine, Automatic Transmission', 'Black', 'Sedan', 'Petrol', 5, 'Midsize', 'New York', 70, true),
('Audi', 'A4', 2022, '2.0L 4-Cylinder Engine, Automatic Transmission', 'Gray', 'Sedan', 'Petrol', 5, 'Midsize', 'Los Angeles', 75, true),
('Mercedes-Benz', 'C-Class', 2024, '2.0L 4-Cylinder Engine, Automatic Transmission', 'Silver', 'Sedan', 'Petrol', 5, 'Midsize', 'San Francisco', 80, true),
('Toyota', 'Camry', 2022, '2.5L 4-Cylinder Engine, Automatic Transmission', 'White', 'Sedan', 'Petrol', 5, 'Midsize', 'Chicago', 60, true),
('Honda', 'Accord', 2023, '1.5L 4-Cylinder Engine, Automatic Transmission', 'Black', 'Sedan', 'Petrol', 5, 'Midsize', 'Houston', 65, true),
('Nissan', 'Altima', 2022, '2.5L 4-Cylinder Engine, Automatic Transmission', 'Red', 'Sedan', 'Petrol', 5, 'Midsize', 'Seattle', 55, true),
('Hyundai', 'Sonata', 2024, '2.5L 4-Cylinder Engine, Automatic Transmission', 'Blue', 'Sedan', 'Petrol', 5, 'Midsize', 'Boston', 60, true),
('Ford', 'Fusion', 2022, '2.0L 4-Cylinder Engine, Automatic Transmission', 'Gray', 'Sedan', 'Petrol', 5, 'Midsize', 'Denver', 50, true),
('Chevrolet', 'Malibu', 2023, '1.5L 4-Cylinder Engine, Automatic Transmission', 'Silver', 'Sedan', 'Petrol', 5, 'Midsize', 'Miami', 55, true),
('Kia', 'Optima', 2022, '2.4L 4-Cylinder Engine, Automatic Transmission', 'Black', 'Sedan', 'Petrol', 5, 'Midsize', 'Dallas', 50, true),
('Volkswagen', 'Passat', 2023, '2.0L 4-Cylinder Engine, Automatic Transmission', 'White', 'Sedan', 'Petrol', 5, 'Midsize', 'San Diego', 55, true),
('BMW', '5 Series', 2024, '3.0L 6-Cylinder Engine, Automatic Transmission', 'Gray', 'Sedan', 'Petrol', 5, 'Fullsize', 'New York', 100, true),
('Audi', 'A6', 2022, '2.0L 4-Cylinder Engine, Automatic Transmission', 'Silver', 'Sedan', 'Petrol', 5, 'Fullsize', 'Los Angeles', 90, true),
('Mercedes-Benz', 'E-Class', 2023, '2.0L 4-Cylinder Engine, Automatic Transmission', 'Black', 'Sedan', 'Petrol', 5, 'Fullsize', 'San Francisco', 110, true),
('Toyota', 'Avalon', 2022, '3.5L V6 Engine, Automatic Transmission', 'White', 'Sedan', 'Petrol', 5, 'Fullsize', 'Chicago', 80, true),
('Honda', 'Pilot', 2024, '3.5L V6 Engine, Automatic Transmission', 'Red', 'SUV', 'Petrol', 8, 'Fullsize', 'Houston', 90, true),
('Ford', 'Explorer', 2023, '2.3L 4-Cylinder Engine, Automatic Transmission', 'Blue', 'SUV', 'Petrol', 7, 'Fullsize', 'Seattle', 85, true),
('Nissan', 'Rogue', 2022, '2.5L 4-Cylinder Engine, Automatic Transmission', 'Gray', 'SUV', 'Petrol', 5, 'Midsize', 'Boston', 70, true);